// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetSessionData } from './types.gen';

export const client = createClient(createConfig());

/**
 * Retrieve session information
 * Get full control of the Browser's Sessions.
 */
export const getSession = <ThrowOnError extends boolean = false>(options: Options<GetSessionData, ThrowOnError>) => {
    return (options?.client ?? client).get<void, unknown, ThrowOnError>({
        ...options,
        url: '/sessions/{sessionId}'
    });
};