// This file is auto-generated by @hey-api/openapi-ts

export type CreateContextRequest = {
    projectId: string;
};

export type CreatedContext = {
    id?: string;
    uploadUrl?: string;
    publicKey?: string;
    cipherAlgorithm?: string;
    initializationVectorSize?: number;
};

export type CreatedSession = {
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    projectId?: string;
    startedAt?: string;
    endedAt?: string;
    expiresAt?: string;
    status?: string;
    proxyBytes?: number;
    avgCpuUsage?: number;
    memoryUsage?: number;
    keepAlive?: boolean;
    contextId?: string;
    region?: string;
    connectUrl?: string;
    seleniumRemoteUrl?: string;
    signingKey?: string;
};

export type CreateSessionRequest = {
    projectId: string;
    extensionId?: string;
    browserSettings?: {
        [key: string]: unknown;
    };
    context?: {
        id?: string;
        persist?: boolean;
    };
    timeout?: number;
    keepAlive?: boolean;
    proxies?: (boolean | Array<(string)>);
    region?: 'us-west-2' | 'us-east-1' | 'eu-central-1' | 'ap-southeast-1';
};

export type region = 'us-west-2' | 'us-east-1' | 'eu-central-1' | 'ap-southeast-1';

export type Session = {
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    projectId?: string;
    startedAt?: string;
    endedAt?: string;
    expiresAt?: string;
    status?: 'RUNNING' | 'ERROR' | 'TIMED_OUT' | 'COMPLETED';
    proxyBytes?: number;
    avgCpuUsage?: number;
    memoryUsage?: number;
    keepAlive?: boolean;
    contextId?: string;
    region?: 'us-west-2' | 'us-east-1' | 'eu-central-1' | 'ap-southeast-1';
};

export type status = 'RUNNING' | 'ERROR' | 'TIMED_OUT' | 'COMPLETED';

export type SessionLog = {
    eventId?: string;
    method?: string;
    pageId?: number;
    request?: {
        timestamp?: number;
        params?: {
            [key: string]: unknown;
        };
        rawBody?: string;
    };
    response?: {
        timestamp?: number;
        result?: {
            [key: string]: unknown;
        };
        rawBody?: string;
    };
    sessionId?: string;
    timestamp?: number;
    frameId?: string;
    loaderId?: string;
};

export type UploadedExtension = {
    id?: string;
    createdAt?: string;
    updatedAt?: string;
    fileName?: string;
    projectId?: string;
};

export type GetSessionsData = {
    headers: {
        'X-BB-API-Key': string;
    };
    query?: {
        status?: 'RUNNING' | 'ERROR' | 'TIMED_OUT' | 'COMPLETED';
    };
};

export type GetSessionsResponse = (Array<Session>);

export type GetSessionsError = unknown;

export type PostSessionsData = {
    body: CreateSessionRequest;
    headers: {
        'X-BB-API-Key': string;
    };
};

export type PostSessionsResponse = (CreatedSession);

export type PostSessionsError = unknown;

export type GetSessionsByIdData = {
    headers: {
        'X-BB-API-Key': string;
    };
    path: {
        id: string;
    };
};

export type GetSessionsByIdResponse = (Session);

export type GetSessionsByIdError = unknown;

export type GetSessionsByIdLogsData = {
    headers: {
        'X-BB-API-Key': string;
    };
    path: {
        id: string;
    };
};

export type GetSessionsByIdLogsResponse = (Array<SessionLog>);

export type GetSessionsByIdLogsError = unknown;

export type PostContextsData = {
    body: CreateContextRequest;
    headers: {
        'X-BB-API-Key': string;
    };
};

export type PostContextsResponse = (CreatedContext);

export type PostContextsError = unknown;

export type PostExtensionsData = {
    body: {
        file?: (Blob | File);
    };
    headers: {
        'X-BB-API-Key': string;
    };
};

export type PostExtensionsResponse = (UploadedExtension);

export type PostExtensionsError = unknown;